name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # TODO: Run tests

      - name: Build x86_64-unknown-linux-gnu
        run: deno compile --allow-read --allow-write --allow-run --target x86_64-unknown-linux-gnu --output $PWD/pokerando-batch.linux-amd64 ./mod.ts

      - name: Build x86_64-pc-windows-msvc
        run: deno compile --allow-read --allow-write --allow-run --target x86_64-pc-windows-msvc --output $PWD/pokerando-batch.windows-amd64.exe ./mod.ts

      - name: Build x86_64-apple-darwin
        run: deno compile --allow-read --allow-write --allow-run --target x86_64-apple-darwin --output $PWD/pokerando-batch.darwin-amd64 ./mod.ts

      - name: Build aarch64-apple-darwin
        run: deno compile --allow-read --allow-write --allow-run --target aarch64-apple-darwin --output $PWD/pokerando-batch.darwin-aarch64 ./mod.ts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pokerando-batch.linux-amd64
            pokerando-batch.windows-amd64.exe
            pokerando-batch.darwin-amd64
            pokerando-batch.darwin-aarch64
            README.md
            LICENSE
